### ISSUE TITLE
Standardize CLI and run() accross ASGI servers

### ISSUE THREAD

**Issue by almarklein** [erm/asgi-examples#2]
I was not sure where to start this discussion; this seems like neutral ground :)

cc @pgjones @tomchristie  

ASGI is great! I can pick a web framework and swap out the server with zero effort. Even the way to run an app from the terminal is the same (kind of).

However, the CLI arguments differ (e.g. `-b` in hypercorn vs `--host` in uvicorn). Both hypercorn and uvicorn have a `run()` method that I can put in my `if __name__ == '__main__'` section. But the signature and way to configure is very different.

Can we please discuss fixing this? (I checked the issue trackers of hypercorn and uvicorn whether this topic was raised before, did not see any, sorry if I missed it.)

To kick this discussion off, here's my proposal:

* Define common CLI args names (at least for the functionality that is shared).
* Have servers define a `some_asgi_server.run_asgi()` function. The `_asgi` suffix makes that non-ASGI servers can potentially expose the function too (via an adapter).
* Allow configuration via keyword arguments to the above function, that have the same names as the CLI args.

**Comment by jordaneremieff** [comment]
As excited as I am that someone is using this repo, I think this discussion would be better posted on the `asgiref` issue tracker https://github.com/django/asgiref/issues. 

Also, great work with asgish - really nice seeing more framework implementations! :)

**Comment by almarklein** [comment]
Good idea! Though perhaps its easier to first have a more informal discussion on how to better align uvicorn and hypercorn. From there, lobbying for this to become part of the spec should also be easier. What do you think?

**Comment by lovelydinosaur** [comment]
@almarklein I probably don't think it should be part of the spec, but I'm not against daphne, uvicorn, and hypercorn taking an informal review of if we'd be happy to use a common set of argument names for the core functionality. Eg. `.run(app, host=..., port=..., **other_server_specfic_stuff)`

What set of arguments would you expect to see as the core functionality?

**Comment by jordaneremieff** [comment]
@almarklein I agree, better to have the informal discussions first - was mainly concerned with visibility of the issue in my suggestion - happy for any general ASGI discussions to take place here.

**Comment by almarklein** [comment]
I just went through the docs of [uvicorn](https://www.uvicorn.org/settings/), [hypercorn](https://pgjones.gitlab.io/hypercorn/usage.html), [daphne](https://github.com/django/daphne/blob/master/daphne/cli.py) and [gunicorn](http://docs.gunicorn.org/en/stable/settings.html). I can see hypercorn drew inspiration from gunicorn, and uvicorn more from daphne :)

I think that the set of common argument names can be limited to the arguments that you'd use in an example, or for simple dev work. For anything more serious, the ability to swap servers that easily is not worth as much.

So actually, this would already be great:
```py
def run(app, *, bind:str, port:int, log_level:str='info', **server_specific_args):
# And these match up with CLI args --bind --port --log-level
```
I wrote "bind" (although I prefer "host" myself) because all except uvicorn use "bind". I wonder whether it makes sense too imply debug mode if `log_level='debug'`? Otherwise we should probably add `debug`.
We could add more, like `loop`, `workers`, `reload`, but they matter less, I think.

I also wrote `run()` instead of `run_asgi` as I suggested earlier; non-asgi frameworks can have e.g. `libname.asgi.run()`.

**Comment by pgjones** [comment]
I'm in general keen on sticking to the Gunicorn names as I'm hoping to make the transition from a Flask+Gunicorn system to Quart+Hypercorn as easy as possible. This said I'm open to suggestions.

**Comment by almarklein** [comment]
I believe that what I suggested would be compatible with Gunicorn. I think what's needed to make it happen is:
* Hypercorn: implement a `hypercorn.run()` as e programmatic entry point.
* Daphne: dito
* Uvicorn: allow `bind` as an alias for `host` (and `--bind` in the CLI).

**Comment by almarklein** [comment]
Ok, I feel a bit silly: `bind` is a combination of host and port, so the "standard signature" becomes even simpler :)

**Comment by almarklein** [comment]
Nope, not feeling silly, just a bit disappointed: `daphne` uses `--bind`, but it represents only the host, the port is to be given seperately :/

**Comment by lovelydinosaur** [comment]
I think I'm gonna take a pass on this, along Andrew's lines.

**Comment by almarklein** [comment]
Fair enough. No hard feelings :)
